// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories.EFCore;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20241204112010_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 15.99m,
                            Title = "Moby Dick"
                        },
                        new
                        {
                            Id = 2,
                            Price = 9.49m,
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            Id = 3,
                            Price = 20.00m,
                            Title = "War and Peace"
                        },
                        new
                        {
                            Id = 4,
                            Price = 10.99m,
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            Id = 5,
                            Price = 14.99m,
                            Title = "1984"
                        },
                        new
                        {
                            Id = 6,
                            Price = 12.49m,
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            Id = 7,
                            Price = 8.99m,
                            Title = "The Catcher in the Rye"
                        },
                        new
                        {
                            Id = 8,
                            Price = 13.49m,
                            Title = "The Hobbit"
                        },
                        new
                        {
                            Id = 9,
                            Price = 11.99m,
                            Title = "Fahrenheit 451"
                        },
                        new
                        {
                            Id = 10,
                            Price = 15.00m,
                            Title = "Brave New World"
                        },
                        new
                        {
                            Id = 11,
                            Price = 18.49m,
                            Title = "Crime and Punishment"
                        },
                        new
                        {
                            Id = 12,
                            Price = 19.99m,
                            Title = "The Brothers Karamazov"
                        },
                        new
                        {
                            Id = 13,
                            Price = 10.99m,
                            Title = "The Odyssey"
                        },
                        new
                        {
                            Id = 14,
                            Price = 12.99m,
                            Title = "The Iliad"
                        },
                        new
                        {
                            Id = 15,
                            Price = 9.99m,
                            Title = "Jane Eyre"
                        },
                        new
                        {
                            Id = 16,
                            Price = 8.49m,
                            Title = "Wuthering Heights"
                        },
                        new
                        {
                            Id = 17,
                            Price = 10.49m,
                            Title = "Great Expectations"
                        },
                        new
                        {
                            Id = 18,
                            Price = 9.49m,
                            Title = "Oliver Twist"
                        },
                        new
                        {
                            Id = 19,
                            Price = 22.00m,
                            Title = "Les Misérables"
                        },
                        new
                        {
                            Id = 20,
                            Price = 17.99m,
                            Title = "Anna Karenina"
                        },
                        new
                        {
                            Id = 21,
                            Price = 11.49m,
                            Title = "A Tale of Two Cities"
                        },
                        new
                        {
                            Id = 22,
                            Price = 23.99m,
                            Title = "Don Quixote"
                        },
                        new
                        {
                            Id = 23,
                            Price = 21.99m,
                            Title = "The Divine Comedy"
                        },
                        new
                        {
                            Id = 24,
                            Price = 7.99m,
                            Title = "The Old Man and the Sea"
                        },
                        new
                        {
                            Id = 25,
                            Price = 19.99m,
                            Title = "Ulysses"
                        },
                        new
                        {
                            Id = 26,
                            Price = 14.49m,
                            Title = "The Sound and the Fury"
                        },
                        new
                        {
                            Id = 27,
                            Price = 12.99m,
                            Title = "Beloved"
                        },
                        new
                        {
                            Id = 28,
                            Price = 13.99m,
                            Title = "Slaughterhouse-Five"
                        },
                        new
                        {
                            Id = 29,
                            Price = 11.99m,
                            Title = "The Sun Also Rises"
                        },
                        new
                        {
                            Id = 30,
                            Price = 10.99m,
                            Title = "On the Road"
                        },
                        new
                        {
                            Id = 31,
                            Price = 8.99m,
                            Title = "Of Mice and Men"
                        },
                        new
                        {
                            Id = 32,
                            Price = 15.49m,
                            Title = "Catch-22"
                        },
                        new
                        {
                            Id = 33,
                            Price = 16.99m,
                            Title = "Lolita"
                        },
                        new
                        {
                            Id = 34,
                            Price = 14.99m,
                            Title = "Middlemarch"
                        },
                        new
                        {
                            Id = 35,
                            Price = 9.49m,
                            Title = "Frankenstein"
                        },
                        new
                        {
                            Id = 36,
                            Price = 10.49m,
                            Title = "Dracula"
                        },
                        new
                        {
                            Id = 37,
                            Price = 11.49m,
                            Title = "Rebecca"
                        },
                        new
                        {
                            Id = 38,
                            Price = 10.99m,
                            Title = "The Picture of Dorian Gray"
                        },
                        new
                        {
                            Id = 39,
                            Price = 9.99m,
                            Title = "Sense and Sensibility"
                        },
                        new
                        {
                            Id = 40,
                            Price = 8.99m,
                            Title = "Persuasion"
                        },
                        new
                        {
                            Id = 41,
                            Price = 9.49m,
                            Title = "Emma"
                        },
                        new
                        {
                            Id = 42,
                            Price = 7.49m,
                            Title = "A Christmas Carol"
                        },
                        new
                        {
                            Id = 43,
                            Price = 12.99m,
                            Title = "David Copperfield"
                        },
                        new
                        {
                            Id = 44,
                            Price = 8.99m,
                            Title = "The Scarlet Letter"
                        },
                        new
                        {
                            Id = 45,
                            Price = 9.49m,
                            Title = "Mansfield Park"
                        },
                        new
                        {
                            Id = 46,
                            Price = 8.49m,
                            Title = "Northanger Abbey"
                        },
                        new
                        {
                            Id = 47,
                            Price = 14.99m,
                            Title = "Bleak House"
                        },
                        new
                        {
                            Id = 48,
                            Price = 10.49m,
                            Title = "Hard Times"
                        },
                        new
                        {
                            Id = 49,
                            Price = 12.49m,
                            Title = "Dombey and Son"
                        },
                        new
                        {
                            Id = 50,
                            Price = 11.99m,
                            Title = "Little Women"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
